@NonCPS
def foo(String b) {
  def version = "${b}"
  def pattern = ~/(\d{1,3})\.(\d{1,3})\.\d{1,4}$/
  def newVersion = version.replaceFirst(pattern) { _,major,minor -> "${major}.${(minor as int) + 1}.0"}
  println "Version ${version} -> new ${newVersion}"
}

      
pipeline {
    agent any
    
    stages {
        
        stage('Example Build') {
            steps {
               script {
                   String b =readFile(file: 'hw2/version')
             
                   foo(b)
                }
            }
        }
    }
}
