@NonCPS
def String foo(String curVer) {
  def version = "${curVer}"
  def pattern = ~/(\d{1,3})\.(\d{1,3})\.\d{1,4}$/
  def newVersion = version.replaceFirst(pattern) { _,major,minor -> "${major}.${(minor as int) + 1}.0"}
  println "Version ${version} -> new ${newVersion}"
  return newVersion
}

      
pipeline {
    agent any
    
    stages {
        
        stage('Example Build') {
            steps {
               script {
                   String curVer =readFile(file: 'hw2/version')
             
                   
                   def updatedVer = foo(curVer)
                 writeFile(file: 'hw2/version', text: "${curVer}")

                }
            }
        }
    }
}
